In [1]:
import pandas as pd

In [2]:
results = pd.read_json("results.jsonl", lines=True)

records = []
for _, row in results.iterrows():
    record = {
        "subs": row["args"]["subs"],
        "lr": row["args"]["lr"],
        "wd": row["args"]["wd"],
        "acc_train": row["acc_train"],
        "acc_val": row["acc_val"],
        "acc_test": row["acc_test"],
    }
    records.append(record)
df = pd.DataFrame.from_records(records)

print(df.shape)
df.head()

(130, 6)

  subs      lr     wd  acc_train  acc_val  acc_test
0    0  0.0005  0.001    100.000   65.856    62.254
1    0  0.0005  0.010     99.984   66.551    63.148
2    0  0.0005  0.100     99.984   65.972    63.327
3    0  0.0010  0.001    100.000   65.162    62.791
4    0  0.0010  0.010    100.000   66.204    61.896

In [3]:
summary = []
for subs, group in df.groupby("subs"):
    idx = group["acc_val"].idxmax()
    summary.append(group.loc[idx])
summary = pd.DataFrame.from_records(summary)
summary

    subs       lr     wd  acc_train  acc_val  acc_test
0      0  0.00030  0.001    100.000   67.245    64.043
1  0,1,2  0.00005  0.001     89.292   49.845    50.183
2      1  0.00020  0.100    100.000   56.377    58.043
3      2  0.00300  0.100     99.957   49.492    50.625

In [4]:
summary_fmt = summary.copy()
summary_fmt = summary_fmt.loc[[0, 2, 3, 1], ["subs", "acc_val", "acc_test"]]
summary_fmt.columns = ["subjects", "val (testid)", "test (shared1k)"]
print(summary_fmt.to_markdown(index=False))

| subjects   |   val (testid) |   test (shared1k) |
|:-----------|---------------:|------------------:|
| 0          |         67.245 |            64.043 |
| 1          |         56.377 |            58.043 |
| 2          |         49.492 |            50.625 |
| 0,1,2      |         49.845 |            50.183 |